### ISSUE TITLE
app crashes during BT configuration on Nougat

### ISSUE THREAD

**Issue by tedder** [ge0rg/aprsdroid#146]
When I select BT for protocol and go into the "preferences" screen to select my device and channel, that causes the app to crash. In other words, when I press "device" or "channel", the app crashes immediately.

I'm assuming it's related to the [new Android permission model](https://developer.android.com/training/permissions/requesting.html). I didn't find any tickets talking about this, though.

I'm on a Nexus 5x, Android 7, stock kernel and not rooted. Basically a very vanilla Android.

**Comment by tedder** [comment]
FWIW, I've ensured mobilink doesn't have the BT connection, I even rebooted to ensure it was not running. Since I'm not rooted I don't think I can send any better logs, though I used the crash reporting (twice) and tagged it with this issue.

**Comment by tedder** [comment]
I was able to get logs via `adb logcat`. Here's what I saw:

```
09-06 17:02:46.998 12460 12460 E AndroidRuntime: FATAL EXCEPTION: main
09-06 17:02:46.998 12460 12460 E AndroidRuntime: Process: org.aprsdroid.app, PID: 12460
09-06 17:02:46.998 12460 12460 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:409)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:371)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2360)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1233)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:142)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:67)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1331)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:619)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: FATAL EXCEPTION: main
09-06 17:02:46.998 12460 12460 E AndroidRuntime: Process: org.aprsdroid.app, PID: 12460
09-06 17:02:46.998 12460 12460 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:409)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:371)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.AbsListView.obtainView(AbsListView.java:2360)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ListView.measureHeightOfChildren(ListView.java:1326)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.ListView.onMeasure(ListView.java:1233)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:142)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:67)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.View.measure(View.java:19730)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1331)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:619)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6077)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
09-06 17:02:46.998 12460 12460 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

The issue is mentioned on SO with a workaround but no answer: http://stackoverflow.com/questions/29782753/nullpointer-with-only-the-gplay-report

And here's the bug report; it's a Nougat issue, it seems like a fix/workaround shouldn't be terrible. https://code.google.com/p/android/issues/detail?id=218945

**Comment by tedder** [comment]
This is actually an "unnamed" BT device. Reminders/summary of the IRC discussion:

```
[08:58] <Ge0rG> tedder: and it also happens if you tap "channel"? That's really funny
[08:58] <tedder> yeah- do you use a different gradient/etc on those? also I can give you bigger logs, I just grepped to narrow it down.
[09:03] <Ge0rG> tedder: I'm just using android's default preference editor for that. The Bluetooth device selection is special, as it creates a MAC address list on the fly, but the channel is a plain number input
[09:04] <Ge0rG> okay, it's a de.duenndns.EditTextPreferenceWithValue - one I wrote myself. But most of them are
[09:04] <Ge0rG> https://github.com/ge0rg/aprsdroid/blob/master/res/xml/backend_bluetooth.xml#L20-L26
...
[09:18] <tedder> I don't know of any BT perm changes, and yes it's paired.
[09:24] <Ge0rG> There is an NPE in the ArrayAdapter that lists BT devices. Maybe there is a nameless device, or one without a MAC address?
[09:25] <tedder> I have something paired without a name. Let me remove it.
[09:25] <tedder> that was it!
[09:25] <tedder> that explains why I saw the ArrayAdapter bit in there..

```
