### ISSUE TITLE
Crash on non-HQ AFSK demodulator

### ISSUE THREAD

**Issue by ge0rg** [ge0rg/aprsdroid#275]
Something is wrong in the NDK build, it doesn't produce the right .so files for arm64 or something?

```
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: org.aprsdroid.app, PID: 8915
E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.aprsdroid.app-2oIcblwzQXGE9fp_oO_t5Q==/base.apk"],nativeLibraryDirectories=[/data/app/org.aprsdroid.app-2oIcblwzQXGE9fp_oO_t5Q==/lib/arm64, /system/lib64, /product/lib64]]] couldn't find "libmultimon.so" 
E AndroidRuntime:       at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E AndroidRuntime:       at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E AndroidRuntime:       at java.lang.System.loadLibrary(System.java:1667)
E AndroidRuntime:       at com.jazzido.PacketDroid.AudioBufferProcessor.<clinit>(AudioBufferProcessor.java:42)
E AndroidRuntime:       at org.aprsdroid.app.AfskInWrapper.<init>(AfskInWrapper.scala:6)
E AndroidRuntime:       at org.aprsdroid.app.AfskUploader.<init>(AfskUploader.scala:25)
E AndroidRuntime:       at org.aprsdroid.app.AprsBackend$$anonfun$3.apply(AprsBackend.scala:54)
E AndroidRuntime:       at org.aprsdroid.app.AprsBackend$$anonfun$3.apply(AprsBackend.scala:54)
E AndroidRuntime:       at org.aprsdroid.app.AprsBackend$.instanciateUploader(AprsBackend.scala:134)
E AndroidRuntime:       at org.aprsdroid.app.AprsService.startPoster(AprsService.scala:175)
E AndroidRuntime:       at org.aprsdroid.app.AprsService.handleStart(AprsService.scala:164)
E AndroidRuntime:       at org.aprsdroid.app.AprsService.onStartCommand(AprsService.scala:96)
E AndroidRuntime:       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4416)
E AndroidRuntime:       at android.app.ActivityThread.access$2000(ActivityThread.java:272)
E AndroidRuntime:       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2087)
E AndroidRuntime:       at android.os.Handler.dispatchMessage(Handler.java:107)
E AndroidRuntime:       at android.os.Looper.loop(Looper.java:237)
E AndroidRuntime:       at android.app.ActivityThread.main(ActivityThread.java:8019)
E AndroidRuntime:       at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E AndroidRuntime:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by ge0rg** [comment]
Fixed in 3be657efc2002a25ee50e38a03c5e0cd253f029b.
