### ISSUE TITLE
Invalid packet causes APRSIS service crash

### ISSUE THREAD

**Issue by na7q** [ge0rg/aprsdroid#390]
```
2024-11-04 06:55:17.945 21185-13267 APRSdroid.Service       org.aprsdroid.app                    D  Incoming post: WICKI>APN382,WIDE2-1,qAR,N7LF-10:!4610.46N12358.67W#PHG5830/W1 Fill-In Wickiup Mtn/Nehalem Valley: KC7ILK-1
2024-11-04 06:55:17.968 21185-13267 APRSdroid.Service       org.aprsdroid.app                    D  parsePacket() unsupported packet: WICKI>APN382,WIDE2-1,qAR,N7LF-10:!4610.46N12358.67W#PHG5830/W1 Fill-In Wickiup Mtn/Nehalem Valley: KC7ILK-1
2024-11-04 06:55:17.969 21185-13267 System.err              org.aprsdroid.app                    W  java.lang.Exception: java.lang.Exception: Bad input decimals: .
2024-11-04 06:55:17.969 21185-13267 System.err              org.aprsdroid.app                    W  	at net.ab0oo.aprs.parser.PositionParser.parseUncompressed(PositionParser.java:136)
2024-11-04 06:55:17.969 21185-13267 System.err              org.aprsdroid.app                    W  	at net.ab0oo.aprs.parser.PositionParser.parseUncompressed(PositionParser.java:141)
2024-11-04 06:55:17.969 21185-13267 System.err              org.aprsdroid.app                    W  	at net.ab0oo.aprs.parser.PositionPacket.<init>(PositionPacket.java:88)
2024-11-04 06:55:17.969 21185-13267 System.err              org.aprsdroid.app                    W  	at net.ab0oo.aprs.parser.Parser.parseBody(Parser.java:126)
2024-11-04 06:55:17.970 21185-13267 System.err              org.aprsdroid.app                    W  	at net.ab0oo.aprs.parser.Parser.parse(Parser.java:84)
2024-11-04 06:55:17.970 21185-13267 System.err              org.aprsdroid.app                    W  	at org.aprsdroid.app.AprsService.parsePacket(AprsService.scala:313)
2024-11-04 06:55:17.970 21185-13267 System.err              org.aprsdroid.app                    W  	at org.aprsdroid.app.AprsService.addPost(AprsService.scala:372)
2024-11-04 06:55:17.970 21185-13267 System.err              org.aprsdroid.app                    W  	at org.aprsdroid.app.AprsService.addPost(AprsService.scala:383)
2024-11-04 06:55:17.970 21185-13267 System.err              org.aprsdroid.app                    W  	at org.aprsdroid.app.AprsService.postAddPost(AprsService.scala:391)
2024-11-04 06:55:17.970 21185-13267 System.err              org.aprsdroid.app                    W  	at org.aprsdroid.app.AprsService.postSubmit(AprsService.scala:401)
2024-11-04 06:55:17.970 21185-13267 System.err              org.aprsdroid.app                    W  	at org.aprsdroid.app.TcpUploader$TcpSocketThread.run(TcpUploader.scala:166)
2024-11-04 06:55:17.971 21185-13267 System.err              org.aprsdroid.app                    W  Caused by: java.lang.Exception: Bad input decimals: .
2024-11-04 06:55:17.971 21185-13267 System.err              org.aprsdroid.app                    W  	at net.ab0oo.aprs.parser.PositionParser.parseDegMin(PositionParser.java:604)
2024-11-04 06:55:17.971 21185-13267 System.err              org.aprsdroid.app                    W  	at net.ab0oo.aprs.parser.PositionParser.parseUncompressed(PositionParser.java:119)
2024-11-04 06:55:17.971 21185-13267 System.err              org.aprsdroid.app                    W  	... 10 more
```

**Comment by na7q** [comment]
Might be caused by my own modifications. So it's a placeholder reminder until I verify.
