### ISSUE TITLE
OSM Mapsforge Crash

### ISSUE THREAD

**Issue by na7q** [ge0rg/aprsdroid#399]
I discovered an issue with mapsforge and the map viewer. It varies a little bit by device. The map will crash if the screen was turned off while the map was the last thing open. However, this only seems to happen on my 2 phones if the swipe lock screen is enabled. Any other, or no lock at all, it doesn't do it.

Disabling the maps hardware acceleration also resolves this issue. Here's the rundown of the problem.

2024-12-30 22:15:54.978 25044-25044 Bitmap                  org.aprsdroid.app                    A  Error, cannot access an invalid/free'd bitmap here!
2024-12-30 22:15:55.241 25044-25044 g.aprsdroid.ap          org.aprsdroid.app                    A  runtime.cc:655] Runtime aborting...
                                                                                                    runtime.cc:655] All threads:
                                                                                                    runtime.cc:655] DALVIK THREADS (20):
                                                                                                    runtime.cc:655] "main" prio=10 tid=1 Runnable
                                                                                                    runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=2 obj=0x7304b338 self=0x7b8bf36010
                                                                                                    runtime.cc:655]   | sysTid=25044 nice=-10 cgrp=default sched=0/0 handle=0x7cb28114f8
                                                                                                    runtime.cc:655]   | state=R schedstat=( 1493337403 327172314 3167 ) utm=113 stm=35 core=7 HZ=100
                                                                                                    runtime.cc:655]   | stack=0x7fdccf1000-0x7fdccf3000 stackSize=8192KB
                                                                                                    runtime.cc:655]   | held mutexes= "abort lock" "mutator lock"(shared held)
                                                                                                    runtime.cc:655]   native: #00 pc 00000000004a53f4  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
                                                                                                    runtime.cc:655]   native: #01 pc 00000000005b42b4  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+372)
                                                                                                    runtime.cc:655]   native: #02 pc 00000000005d1854  /apex/com.android.art/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+924)
                                                                                                    runtime.cc:655]   native: #03 pc 00000000005cb6c4  /apex/com.android.art/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+532)
                                                                                                    runtime.cc:655]   native: #04 pc 00000000005ca638  /apex/com.android.art/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+1352)
                                                                                                    runtime.cc:655]   native: #05 pc 000000000056462c  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+1876)
                                                                                                    runtime.cc:655]   native: #06 pc 0000000000013ab0  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+80)
                                                                                                    runtime.cc:655]   native: #07 pc 0000000000006ec8  /system/lib64/liblog.so (__android_log_assert+336)
                                                                                                    runtime.cc:655]   native: #08 pc 00000000001a9fd4  /system/lib64/libhwui.so (android::CanvasJNI::drawBitmapMatrix(_JNIEnv*, _jobject*, long, long, long, long)+68)
                                                                                                    runtime.cc:655]   at android.graphics.BaseRecordingCanvas.nDrawBitmapMatrix(Native method)
                                                                                                    runtime.cc:655]   at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:78)
                                                                                                    runtime.cc:655]   at org.mapsforge.v3.android.maps.overlay.Overlay.draw(Overlay.java:139)
                                                                                                    runtime.cc:655]   - locked <0x07b55e90> (a android.graphics.Matrix)
                                                                                                    runtime.cc:655]   at org.mapsforge.v3.android.maps.MapView.onDraw(MapView.java:665)
                                                                                                    runtime.cc:655]   - locked <0x0e695389> (a org.mapsforge.v3.android.maps.overlay.OverlayList)
                                                                                                    runtime.cc:655]   at android.view.View.draw(View.java:22350)
                                                                                                    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21226)
                                                                                                    runtime.cc:655]   at android.view.View.draw(View.java:22081)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21217)
                                                                                                    runtime.cc:655]   at android.view.View.draw(View.java:22081)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21217)
                                                                                                    runtime.cc:655]   at android.view.View.draw(View.java:22081)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
                                                                                                    runtime.cc:655]   at android.view.View.draw(View.java:22353)
                                                                                                    runtime.cc:655]   at com.android.internal.widget.ActionBarOverlayLayout.draw(ActionBarOverlayLayout.java:517)
                                                                                                    runtime.cc:655]   at android.view.View.updateDisplayListIfDirty(View.java:21226)
                                                                                                    runtime.cc:655]   at android.view.View.draw(View.java:22081)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
                                                                                                    runtime.cc:655]   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)

**Comment by na7q** [comment]
Also part of that

2024-12-30 22:15:55.726  1392-25193 ActivityTaskManager     system_server                        W    Force finishing activity org.aprsdroid.app/.MapAct
2024-12-30 22:15:55.817  1392-4293  WindowManager           system_server                        I  WIN DEATH: Window{50ad1ff u0 org.aprsdroid.app/org.aprsdroid.app.MapAct}
2024-12-30 22:15:55.818  1392-4293  InputDispatcher         system_server                        W  Attempted to unregister already unregistered input channel '50ad1ff org.aprsdroid.app/org.aprsdroid.app.MapAct (server)'
2024-12-30 22:15:56.228  1392-1462  ActivityTaskManager     system_server                        W  Activity top resumed state loss timeout for ActivityRecord{c30346e u0 org.aprsdroid.app/.MapAct t-1 f}}
